RIGHT_HANDSHAKE = "DWP-Handshake".encode("ascii")

PACKET_HEADER_SIZE = 11

PACKET_FLAG_CMD = 0x00
PACKET_FLAG_REPLY = 0x80

CMDSET_VM = 1
CMDSET_OBJECT = 9
CMDSET_STRING = 10
CMDSET_THREAD = 11
CMDSET_ARRAY = 13
CMDSET_EVENT_REQUEST = 15
CMDSET_STACK = 16
CMDSET_APPDOMAIN = 20
CMDSET_ASSEMBLY = 21
CMDSET_METHOD = 22
CMDSET_TYPE = 23
CMDSET_MODULE = 24
CMDSET_EVENT = 64

CMD_VM_GET_VERSION = 1
CMD_VM_GET_ALL_THREADS = 2
CMD_VM_SUSPEND = 3
CMD_VM_RESUME = 4
CMD_VM_EXIT = 5
CMD_VM_DISPOSE = 6
CMD_VM_INVOKE_METHOD = 7
CMD_VM_SET_PROTOCOL_VERSION = 8
CMD_VM_ABORT_INVOKE = 9
CMD_VM_SET_KEEAPALIVE = 10
CMD_VM_GET_TYPES_FOR_SOURCE_FILE = 11
CMD_VM_GET_TYPES = 12

CMD_OBJ_GET_TYPE = 1
CMD_OBJ_GET_VALUES = 2
CMD_OBJ_IS_COLLECTED = 3
CMD_OBJ_GET_ADDRESS = 4
CMD_OBJ_GET_DOMAIN = 5
CMD_OBJ_SET_VALUES = 6

CMD_STR_GET_VALUE = 1
CMD_STR_GET_LENGTH = 2
CMD_STR_GET_CHARS = 3

CMD_THREAD_GET_FRAME_INFO = 1
CMD_THREAD_GET_NAME = 2
CMD_THREAD_GET_STATE = 3
CMD_THREAD_GET_INFO = 4
CMD_THREAD_GET_ID = 5
CMD_THREAD_GET_TID = 6

CMD_ARRAY_GET_LENGTH = 1
CMD_ARRAY_GET_VALUES = 2
CMD_ARRAY_SET_VALUES = 3

CMD_EVENT_REQUEST_SET = 1
CMD_EVENT_REQUEST_CLEAR = 2
CMD_EVENT_REQUEST_CLEAR_ALL_BREAKPOINTS = 3

CMD_STACK_GET_VALUES = 1
CMD_STACK_GET_THIS = 2
CMD_STACK_SET_VALUES = 3

CMD_APPDOMAIN_GET_ROOT = 1
CMD_APPDOMAIN_GET_NAME = 2
CMD_APPDOMAIN_GET_ASSEMBLIES = 3
CMD_APPDOMAIN_GET_ENTRY_ASSEMBLY = 4
CMD_APPDOMAIN_CREATE_STRING = 5
CMD_APPDOMAIN_GET_CORLIB_ASSEMBLY = 6
CMD_APPDOMAIN_CREATE_BOXED_VALUE = 7

CMD_ASSEMBLY_GET_LOCATION = 1
CMD_ASSEMBLY_GET_ENTRY = 2
CMD_ASSEMBLY_GET_MANIFEST_MODULE = 3
CMD_ASSEMBLY_GET_OBJECT = 4
CMD_ASSEMBLY_GET_TYPE = 5
CMD_ASSEMBLY_GET_NAME = 6

CMD_METHOD_GET_NAME = 1
CMD_METHOD_GET_DECLARING_TYPE = 2
CMD_METHOD_GET_DEBUG_INFO = 3
CMD_METHOD_GET_PARAM_INFO = 4
CMD_METHOD_GET_LOCALS_INFO = 5
CMD_METHOD_GET_INFO = 6
CMD_METHOD_GET_BODY = 7
CMD_METHOD_RESOLVE_TOKEN = 8

CMD_TYPE_GET_INFO = 1
CMD_TYPE_GET_METHODS = 2
CMD_TYPE_GET_FIELDS = 3
CMD_TYPE_GET_VALUES = 4
CMD_TYPE_GET_OBJECT = 5
CMD_TYPE_GET_SOURCE_FILES = 6
CMD_TYPE_SET_VALUES = 7
CMD_TYPE_IS_ASSIGNABLE_FROM = 8
CMD_TYPE_GET_PROPERTIES = 9
CMD_TYPE_GET_CATTRS = 10
CMD_TYPE_GET_FIELD_CATTRS = 11
CMD_TYPE_GET_PROPERTY_CATTRS = 12
CMD_TYPE_GET_SOURCE_FILES_2 = 13
CMD_TYPE_GET_VALUES_2 = 14

CMD_MODULE_GET_INFO = 1

CMD_EVENT_COMPOSITE = 100

RESULT_SUCCESS = 0
RESULT_INVALID_OBJECT = 20
RESULT_INVALID_FIELD_ID = 25
RESULT_INVALID_FRAME_ID = 30
RESULT_NOT_IMPLEMENTED = 100
RESULT_NOT_SUSPENDED = 101
RESULT_INVALID_ARGUMENT = 102
RESULT_UNLOADED = 103
RESULT_NO_INVOCATION = 104
RESULT_ABSENT_INFORMATION = 105
RESULT_WRONG_IL_OFFSET = 106

EVENT_KIND_VM_START = 0
EVENT_KIND_VM_DEATH = 1
EVENT_KIND_THREAD_START = 2
EVENT_KIND_THREAD_DEATH = 3
EVENT_KIND_APPDOMAIN_CREATE = 4
EVENT_KIND_APPDOMAIN_UNLOAD = 5
EVENT_KIND_METHOD_ENTRY = 6
EVENT_KIND_METHOD_EXIT = 7
EVENT_KIND_ASSEMBLY_LOAD = 8
EVENT_KIND_ASSEMBLY_UNLOAD = 9
EVENT_KIND_BREAKPOINT = 10
EVENT_KIND_STEP = 11
EVENT_KIND_TYPE_LOAD = 12
EVENT_KIND_EXCEPTION = 13
EVENT_KIND_KEEPALIVE = 14
EVENT_KIND_USER_BREAK = 15
EVENT_KIND_USER_LOG = 16
EVENT_KIND_COMPOSITE = 100

EVENT_FRIENDLY_NAME = {
    EVENT_KIND_THREAD_START: "THREAD_START",
    EVENT_KIND_THREAD_DEATH: "THREAD_DEATH",
    EVENT_KIND_VM_DEATH: "VM_DEATH",
    EVENT_KIND_VM_START: "VM_START",
    EVENT_KIND_APPDOMAIN_CREATE: "APPDOMAIN_CREATE",
    EVENT_KIND_APPDOMAIN_UNLOAD: "APPDOMAIN_UNLOAD",
    EVENT_KIND_METHOD_ENTRY: "METHOD_ENTRY",
    EVENT_KIND_METHOD_EXIT: "METHOD_EXIT",
    EVENT_KIND_ASSEMBLY_LOAD: "ASSEMBLY_LOAD",
    EVENT_KIND_ASSEMBLY_UNLOAD: "ASSEMBLY_UNLOAD",
    EVENT_KIND_TYPE_LOAD: "TYPE_LOAD",
    EVENT_KIND_BREAKPOINT: "BREAKPOINT",
    EVENT_KIND_STEP: "STEP",
    EVENT_KIND_EXCEPTION: "EXCEPTION"
}

SUSPEND_POLICY_NONE = 0
SUSPEND_POLICY_EVENT_THREAD = 1
SUSPEND_POLICY_ALL = 2

MOD_KIND_COUNT = 1
MOD_KIND_THREAD_ONLY = 3
MOD_KIND_LOCATION_ONLY = 7
MOD_KIND_EXCEPTION_ONLY = 8
MOD_KIND_STEP = 10
MOD_KIND_ASSEMBLY_ONLY = 11
MOD_KIND_SOURCE_FILE_ONLY = 12
MOD_KIND_TYPE_NAME_ONLY = 13

STEP_DEPTH_INTO = 0
STEP_DEPTH_OVER = 1
STEP_DEPTH_OUT = 2

STEP_SIZE_MIN = 0
STEP_SIZE_LINE = 1

TOKEN_TYPE_STRING = 0
TOKEN_TYPE_TYPE = 1
TOKEN_TYPE_FIELD = 2
TOKEN_TYPE_METHOD = 3
TOKEN_TYPE_UNKNOWN = 4

FRAME_FLAG_DEBUGGER_INFOKE = 1

INVOKE_FLAG_DISABLE_BREAKPOINTS = 1
INVOKE_FLAG_SINGLE_THREADED = 2

THREAD_STATE_RUNNING = 0
THREAD_STATE_STOP_REQUESTED = 1
THREAD_STATE_SUSPEND_REQUESTED = 2
THREAD_STATE_BACKGROUND = 4
THREAD_STATE_UNSTARTED = 8
THREAD_STATE_STOPPED = 16
THREAD_STATE_WAIT_SLEEP_JOIN = 32
THREAD_STATE_SUSPENDED = 64
THREAD_STATE_ABORT_REQUESTED = 128
THREAD_STATE_ABORTED = 256

CALLING_CONVENTION_STANDARD = 1
CALLING_CONVENTION_VAR_ARGS = 2
CALLING_CONVENTION_ANY = 3
CALLING_CONVENTION_HAS_THIS = 32
CALLING_CONVENTION_EXPLICIT_THIS = 64

MONO_TYPE_VOID = 0x01
MONO_TYPE_BOOLEAN = 0x02
MONO_TYPE_I1 = 0x04
MONO_TYPE_U1 = 0x05
MONO_TYPE_CHAR = 0x03
MONO_TYPE_I2 = 0x06
MONO_TYPE_U2 = 0x07
MONO_TYPE_I4 = 0x08
MONO_TYPE_U4 = 0x09
MONO_TYPE_I8 = 0x0a
MONO_TYPE_U8 = 0x0b
MONO_TYPE_R4 = 0x0c
MONO_TYPE_R8 = 0x0d
MONO_TYPE_PTR = 0x0f
MONO_TYPE_STRING = 0x0e
MONO_TYPE_SZARRAY = 0x1d
MONO_TYPE_OBJECT = 0x1c
MONO_TYPE_CLASS = 0x12
MONO_TYPE_ARRAY = 0x14
MONO_TYPE_VALUETYPE = 0x11
MONO_TYPE_GENERICINST = 0x15
MONO_TYPE_NULL = 0xf0
MONO_TYPE_TYPE = 0xf1

TYPE_ATTR_VISIBILITY_MASK = 7,
TYPE_ATTR_NOT_PUBLIC = 0
TYPE_ATTR_PUBLIC = 1
TYPE_ATTR_NESTED_PUBLIC = 2
TYPE_ATTR_NESTED_PRIVATE = 3
TYPE_ATTR_NESTED_FAMILY = 4
TYPE_ATTR_NESTED_ASSEMBLY = 5
TYPE_ATTR_NESTED_FAM_AND_ASSEM = 6
TYPE_ATTR_NESTED_FAM_OR_ASSEM = 7
TYPE_ATTR_LAYOUT_MASK = 24
TYPE_ATTR_AUTO_LAYOUT = 0
TYPE_ATTR_SEQUENTIAL_LAYOUT = 8
TYPE_ATTR_EXPLICIT_LAYOUT = 16
TYPE_ATTR_CLASS_SEMANTICS_MASK = 32
TYPE_ATTR_CLASS = 0
TYPE_ATTR_INTERFACE = 32
TYPE_ATTR_ABSTRACT = 128
TYPE_ATTR_SEALED = 256
TYPE_ATTR_SPECIAL_NAME = 1024
TYPE_ATTR_IMPOT = 4096
TYPE_ATTR_SERIALIZABLE = 8192
TYPE_ATTR_STRING_FORMAT_CLASS = 196608
TYPE_ATTR_ANSI_CLASS = 0
TYPE_ATTR_UNICODE_CLASS = 65536
TYPE_ATTR_AUTO_CLASS = 131072
TYPE_ATTR_BEFORE_FIELD_INIT = 1048576
TYPE_ATTR_REVERSED_MASK = 264192
TYPE_ATTR_RT_SPECIAL_NAME = 2048
TYPE_ATTR_HAS_SECURITY = 262144
TYPE_ATTR_CUSTOM_FORMAT_CLASS = 196608
TYPE_ATTR_CUSTOM_FORMAT_MASK = 12582912
