
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'BY DOTNET MEMORY PROCESS QUERY THREAD USAGEquery : QUERY DOTNET MEMORY USAGE BY ENTITY\n    ENTITY : PROCESS\n           | THREAD\n    '
    
_lr_action_items = {'QUERY':([0,],[2,]),'$end':([1,7,8,9,],[0,-1,-2,-3,]),'DOTNET':([2,],[3,]),'MEMORY':([3,],[4,]),'USAGE':([4,],[5,]),'BY':([5,],[6,]),'PROCESS':([6,],[8,]),'THREAD':([6,],[9,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'query':([0,],[1,]),'ENTITY':([6,],[7,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> query","S'",1,None,None,None),
  ('query -> QUERY DOTNET MEMORY USAGE BY ENTITY','query',6,'p_query','lexer.py',43),
  ('ENTITY -> PROCESS','ENTITY',1,'p_entity','lexer.py',52),
  ('ENTITY -> THREAD','ENTITY',1,'p_entity','lexer.py',53),
]
